#!/bin/bash

# Auto-Build Environment Setup
# Production CORS Security Configuration
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Feature: Production CORS Security Configuration"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Checking environment..."

# Check if .env file exists
if [ ! -f .env ]; then
    echo -e "${YELLOW}Warning: .env file not found${NC}"
    echo "Creating .env from .env.temp..."
    if [ -f .env.temp ]; then
        cp .env.temp .env
        echo -e "${GREEN}.env created${NC}"
    else
        echo -e "${RED}Error: .env.temp not found${NC}"
        exit 1
    fi
fi

# Check node_modules
if [ ! -d "node_modules" ]; then
    echo "Installing dependencies..."
    npm install
fi

# ============================================
# START API SERVICE
# ============================================

echo ""
echo "========================================"
echo "Starting API Service"
echo "========================================"

# Start API in development mode
echo "Starting API on port 3001..."
npm run api:dev &
API_PID=$!

# Wait for API to be ready
wait_for_service 3001 "API"

if [ $? -eq 0 ]; then
    echo -e "${GREEN}API started successfully${NC}"
else
    echo -e "${RED}API failed to start${NC}"
    exit 1
fi

# ============================================
# ENVIRONMENT READY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Services:"
echo "  API:      http://localhost:3001"
echo "  Health:   http://localhost:3001/health"
echo ""
echo "CORS Security Feature:"
echo "  - CHROME_EXTENSION_ID: ${CHROME_EXTENSION_ID:-'NOT SET (see .env)'}"
echo "  - CORS_ORIGINS: ${CORS_ORIGINS:-'http://localhost:3000'}"
echo ""
echo "Testing Instructions:"
echo "  1. Test health check: curl http://localhost:3001/health"
echo "  2. Test CORS from browser console"
echo "  3. Verify extension ID validation in production mode"
echo ""
echo "Press Ctrl+C to stop all services"
echo ""

# Handle shutdown
trap "echo 'Stopping services...'; kill $API_PID 2>/dev/null; exit 0" INT TERM

# Keep script running
wait
